### ISSUE TITLE
What are you using to create your site?

### ISSUE THREAD

**Issue by MichaelJAndy** [chrisalbon/Data-Science-For-Political-And-Social-Phenomena#28]
Hey, I think your site it really awesome. I'm wondering what you're using to create it? 

The source here is raw HTML but I'm guessing you're actually writing it in some form of markdown and then converting it over. Is the output from something like https://github.com/hyde/hyde or http://getpelican.com/ ? (maybe Jekyll, but I'd assume that you'd use a Python library and not a Ruby one).

Would love to know - also the actual content of your site is amazing and I've found it so useful, keep up the great work!

**Comment by chrisalbon** [comment]
Hey Michael,

Thanks for the kind words!

My workflow is = Jupyter Notebook - > export to markdown -> convert to to html using Pelican. Any static site generator will work, I chose Pelican because I use a lot of Python.

**Comment by MichaelJAndy** [comment]
Thanks Chris, you're awesome!

**Comment by chrisalbon** [comment]
Thanks!
