### ISSUE TITLE
Wrong Date

### ISSUE THREAD

**Issue by davidwin93** [chrisalbon/Data-Science-For-Political-And-Social-Phenomena#3]
[Link to Page](https://github.com/chrisalbon/peripheral_brain/python/pandas_moving_average.html)
The date reads December 1 2016 which is a few months into the feature.

**Comment by blindmelon** [comment]
I was just coming to point out the same thing for http://chrisalbon.com/projects/data_science_reading_list.html - I actually spent a minute questioning what year it was and how old I am.

**Comment by chrisalbon** [comment]
Haha, sorry all. I chose the wrong date, I've fixed it.
