### ISSUE TITLE
Create column with missing data

### ISSUE THREAD

**Issue by jbandlow** [chrisalbon/Data-Science-For-Political-And-Social-Phenomena#5]
Love your site!  I happened to come across this: https://github.com/chrisalbon/peripheral_brain/blob/gh-pages/python/pandas_missing_data.html#L298 and wanted to point out that `df['location'] = np.nan` is more idiomatic than `df['location'] = [np.nan, np.nan, np.nan, np.nan, np.nan]`.

**Comment by chrisalbon** [comment]
Awesome! Thanks! Fixed!
