### ISSUE TITLE
List Unique Values In A Pandas Column option

### ISSUE THREAD

**Issue by bobhaffner** [chrisalbon/Data-Science-For-Political-And-Social-Phenomena#6]
http://chrisalbon.com/python/pandas_list_unique_values_in_column.html

Instead of 
```
#List unique values in the df['name'] column
pd.unique(df.name.ravel())
```
You could do
```
#List unique values in the df['name'] column
df.name.unique()
```

**Comment by chrisalbon** [comment]
Thanks Bob!

That is a way better way. Corrected! 
http://chrisalbon.com/python/pandas_list_unique_values_in_column.html

Bob Haffner wrote:

**Comment by bobhaffner** [comment]
Good deal.  Thanks for the awesome resource by the way
